export const apiPath = {
  LOGIN: "api/master/login",
  VERIFY_LINK_SET: "api/master/verify-password-link/set",
  VERIFY_LINK_RESET: "api/master/verify-password-link/reset",
  GET_PRACTICE_PROFILE: "api/master/practice",
  UPDATE_PRACTICE_PROFILE: "api/master/practice",
  GET_LOCATION_DETAILS: "api/master/location/all",
  GET_ALL_STATES: "api/master/states",
  ADD_LOCATION: "api/master/location",
  EDIT_LOCATION: "api/master/location",
  EDIT_LOCATION_STATUS: "api/master/location/change-status",
  GET_ALL_STAFF: "api/master/staff/all",
  ADD_STAFF: "api/master/staff",
  EDIT_STAFF: "api/master/staff",
  EDIT_STAFF_STATUS: "api/master/staff/change-status",
  GET_ALL_CONTACTS: "api/master/contacts/all",
  ADD_CONTACT: "api/master/contacts",
  EDIT_CONTACT: "api/master/contacts",
  GET_ALL_WORK_LOCATION_CLINICIAN: "api/master/clinician/locations",
  GET_ALL_SUPERVISOR_CLINICIAN: "api/master/clinician/supervisors",
  GET_ALL_CLINICIAN_DETAILS: "api/master/clinician/all",
  ADD_CLINICIAN: "api/master/clinician",
  EDIT_CLINICIAN: "api/master/clinician",
  EDIT_CLINICIAN_STATUS: "api/master/clinician/change-status",
  GET_CLINICIAN_BY_ID: "api/master/clinician",
  GET_LOCATION_DETAILS_BY_ID: "api/master/location",
};
