export enum UnsubscribeReason {
  CONTENT_NOT_RELEVANT = "CONTENT_NOT_RELEVANT",
  TOO_MANY_EMAILS = "TOO_MANY_EMAILS",
  FOUND_ALTERNATIVE_SERVICES = "FOUND_ALTERNATIVE_SERVICES",
  NO_LONGER_INTERESTED = "NO_LONGER_INTERESTED",
  OTHER = "OTHER"
}
