export const staffMockData = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    contact: "+1 555-123-4567",
    role: "Administrator",
    status: "Active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    contact: "+1 555-987-6543",
    role: "Nurse",
    status: "Active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    name: "Michael Davis",
    email: "m.davis@example.com",
    contact: "+1 555-456-7890",
    role: "Doctor",
    status: "Inactive",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export const clinicianMockData = [
  {
    name: "Jessica Williams",
    email: "j.williams@healthcare.org",
    contact: "+1 555-234-5678",
    npinumber: "1234567890",
    worklocation: "Main Hospital",
    status: "Active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    name: "Robert Chen",
    email: "robert.chen@healthcare.org",
    contact: "+1 555-876-5432",
    npinumber: "2345678901",
    worklocation: "West Wing Clinic",
    status: "Active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    name: "Amara Patel",
    email: "a.patel@healthcare.org",
    contact: "+1 555-345-6789",
    npinumber: "3456789012",
    worklocation: "East Side Medical Center",
    status: "Inactive",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    name: "Thomas Rodriguez",
    email: "t.rodriguez@healthcare.org",
    contact: "+1 555-654-3210",
    npinumber: "4567890123",
    worklocation: "South Branch Office",
    status: "Active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export const contactMockData = [
  {
    uuid: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 555-111-2222",
    fax: "+1 555-222-3333",
    contact: "502-603-0020",
    address: "123 Main St, City, State 12345",
    contacttype: "Referral",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    uuid: "2",
    name: "Oklahoma Diagnostics",
    email: "jane.smith@example.com",
    phone: "+1 555-444-5555",
    fax: "+1 555-666-7777",
    contact: "502-603-0021",
    address: "456 Oak Ave, City, State 12345",
    contacttype: "Lab",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export const rolesMockData = [
  {
    description: "Patients",
  },
  {
    description: "Create Edit View Patient",
    uuid: "create-edit-view-patient",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Patients",
    uuid: "view-patients",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Share Patients",
    uuid: "share-patients",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Appointments",
  },
  {
    description: "Create Appointments",
    uuid: "create-appointments",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Appointments",
    uuid: "view-appointments",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Appointment Clinician Selection",
    uuid: "appointment-clinician-selection",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Availability",
  },
  {
    description: "Create Availability",
    uuid: "create-availability",
    superAdmin: false,
    clinician: true,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Availability",
    uuid: "view-availability",
    superAdmin: false,
    clinician: true,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Have Availability",
    uuid: "have-availability",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Documents - Intake",
  },
  {
    description: "Edit Intake Documents",
    // isCategory: true,
    uuid: "cat-documents-intake",
    superAdmin: true,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
];

export const locationTableData = [
  {
    locationName: "Main Clinic",
    contactNumber: "502-603-0020",
    email: "main@practiceeasily.com",
    groupNPI: "1234567890",
    fax: "502-603-0021",
    address: "205 Champion Way Suite 11 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Downtown Branch",
    contactNumber: "502-603-0022",
    email: "downtown@practiceeasily.com",
    groupNPI: "0987654321",
    fax: "502-603-0023",
    address: "123 Main Street Suite 4B Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Northside Clinic",
    contactNumber: "502-603-0024",
    email: "northside@practiceeasily.com",
    groupNPI: "1357924680",
    fax: "502-603-0025",
    address: "4580 North Ave Suite 201 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Southside Medical",
    contactNumber: "502-603-0026",
    email: "southside@practiceeasily.com",
    groupNPI: "2468135790",
    fax: "502-603-0027",
    address: "789 South Blvd Suite 30 Georgetown, KY 40324",
    status: "inactive",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Eastside Health Center",
    contactNumber: "502-603-0028",
    email: "eastside@practiceeasily.com",
    groupNPI: "3698521470",
    fax: "502-603-0029",
    address: "623 East Main Road Suite 5 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Westside Family Practice",
    contactNumber: "502-603-0030",
    email: "westside@practiceeasily.com",
    groupNPI: "7539514682",
    fax: "502-603-0031",
    address: "1024 West Park Avenue Suite 15 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export const practiceData = {
  name: "Practice Easily",
  clinicNPI: "2365987458",
  emailID: "abc@example.com",
  taxType: "TIN",
  taxonomyCode: "1234567890",
  taxNumber: "123456 (TIN)",
  address: "205 Champion Way Suite 11 Georgetown, KY 40324",
  contactNumber: "502-603-0020",
};

export const feeScheduleMockData = [
  {
    procedureCode: "Reschedule Appointment",
    rate: "$10",
    codeType: "-",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    procedureCode: "No Show",
    rate: "$20",
    codeType: "-",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    procedureCode: "Cancel Appointment",
    rate: "$30",
    codeType: "-",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    procedureCode: "99088",
    rate: "$80",
    codeType: "CPT",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    procedureCode: "99077",
    rate: "$60",
    codeType: "Self Pay",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export interface PatientData {
  mrn: string;
  patientName: string;
  dob: string;
  emailId: string;
  contactNumber: string;
  clinician: string;
  memberSince: string;
  paymentMethod: string;
  status: "NEW" | "ACTIVE" | "DISCHARGED";
}

export const PATIENT_MOCK_DATA: PatientData[] = [
  {
    mrn: "AS2456",
    patientName: "Robert Fox",
    dob: "1/31/14",
    emailId: "tg03@example.com",
    contactNumber: "(603) 555-0123",
    clinician: "Theresa Webb (Psychiatrist)",
    memberSince: "6/21/19",
    paymentMethod: "Self Pay",
    status: "NEW",
  },
  {
    mrn: "SF5132",
    patientName: "Eleanor Pena",
    dob: "8/2/19",
    emailId: "js02@example.com",
    contactNumber: "(217) 555-0113",
    clinician: "Kathryn Murphy (Custodian)",
    memberSince: "1/31/14",
    paymentMethod: "United Healthcare",
    status: "ACTIVE",
  },
  {
    mrn: "DF5686",
    patientName: "Marvin McKinney",
    dob: "1/28/17",
    emailId: "js02@example.com",
    contactNumber: "(208) 555-0112",
    clinician: "Jacob Jones (Supervisor)",
    memberSince: "9/4/12",
    paymentMethod: "United Healthcare",
    status: "DISCHARGED",
  },
  {
    mrn: "RT4521",
    patientName: "Arlene McCoy",
    dob: "8/16/13",
    emailId: "sf08@example.com",
    contactNumber: "(239) 555-0108",
    clinician: "Eleanor Pena(Psychiatrist)",
    memberSince: "7/11/19",
    paymentMethod: "Self Pay",
    status: "ACTIVE",
  },
  {
    mrn: "HJ4586",
    patientName: "Ralph Edwards",
    dob: "7/11/19",
    emailId: "tg03@example.com",
    contactNumber: "(629) 555-0129",
    clinician: "Marvin McKinney (Custodian)",
    memberSince: "7/27/13",
    paymentMethod: "United Healthcare",
    status: "DISCHARGED",
  },
  {
    mrn: "WK7823",
    patientName: "Cameron Wilson",
    dob: "3/15/15",
    emailId: "cw15@example.com",
    contactNumber: "(445) 555-0178",
    clinician: "Sarah Johnson (Therapist)",
    memberSince: "4/30/20",
    paymentMethod: "Blue Cross",
    status: "ACTIVE",
  },
  {
    mrn: "LM9234",
    patientName: "Diana Martinez",
    dob: "11/22/16",
    emailId: "dm22@example.com",
    contactNumber: "(556) 555-0192",
    clinician: "Michael Davis (Psychiatrist)",
    memberSince: "8/15/21",
    paymentMethod: "Aetna",
    status: "NEW",
  },
  {
    mrn: "PQ4567",
    patientName: "Thomas Anderson",
    dob: "5/7/18",
    emailId: "ta07@example.com",
    contactNumber: "(667) 555-0145",
    clinician: "Jessica Williams (Supervisor)",
    memberSince: "2/28/22",
    paymentMethod: "Self Pay",
    status: "ACTIVE",
  },
  {
    mrn: "BC8912",
    patientName: "Sophia Chen",
    dob: "9/30/12",
    emailId: "sc30@example.com",
    contactNumber: "(778) 555-0167",
    clinician: "Robert Chen (Therapist)",
    memberSince: "10/15/20",
    paymentMethod: "Cigna",
    status: "DISCHARGED",
  },
  {
    mrn: "XY3456",
    patientName: "James Taylor",
    dob: "6/25/17",
    emailId: "jt25@example.com",
    contactNumber: "(889) 555-0134",
    clinician: "Amara Patel (Psychiatrist)",
    memberSince: "3/10/21",
    paymentMethod: "Medicare",
    status: "ACTIVE",
  },
];

export const APPOINTMENT_MOCK_DATA = [
  {
    clientName: "Marvin McKinney",
    apptMode: "Location 1",
    time: "5: 40 am (15 Mins)",
    apptType: "New",
    intakeForm: "PENDING",
    dob: "1/15/12",
    contactNo: "302 555-0107",
    clinician: "Wade Warren",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Floyd Miles",
    apptMode: "Virtual",
    time: "5: 45 am (15 Mins)",
    apptType: "Follow Up",
    intakeForm: "PENDING",
    dob: "4/21/12",
    contactNo: "208 555-0112",
    clinician: "Eleanor Pena",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Jacob Jones",
    apptMode: "Virtual",
    time: "6: 00 am (15 Mins)",
    apptType: "New",
    intakeForm: "PENDING",
    dob: "11/7/16",
    contactNo: "219 555-0114",
    clinician: "Floyd Miles",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Cody Fisher",
    apptMode: "Location 1",
    time: "6: 30 am (15 Mins)",
    apptType: "Follow Up",
    intakeForm: "SCHEDULED",
    dob: "5/19/12",
    contactNo: "684 555-0102",
    clinician: "Albert Flores",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Dianne Russell",
    apptMode: "Location 2",
    time: "6: 45 am (15 Mins)",
    apptType: "New",
    intakeForm: "SCHEDULED",
    dob: "8/30/14",
    contactNo: "303 555-0105",
    clinician: "Annette Black",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Annette Black",
    apptMode: "Virtual",
    time: "7: 00 am (15 Mins)",
    apptType: "Follow Up",
    intakeForm: "SCHEDULED",
    dob: "10/6/13",
    contactNo: "907 555-0101",
    clinician: "Jane Cooper",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Theresa Webb",
    apptMode: "Virtual",
    time: "7: 15 am (15 Mins)",
    apptType: "Follow Up",
    intakeForm: "COMPLETED",
    dob: "12/10/13",
    contactNo: "629 555-0129",
    clinician: "Darrell Steward",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Kathryn Murphy",
    apptMode: "Location 1",
    time: "7: 30 am (15 Mins)",
    apptType: "New",
    intakeForm: "COMPLETED",
    dob: "7/11/19",
    contactNo: "217 555-0113",
    clinician: "Jenny Wilson",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Cameron Williamson",
    apptMode: "Location 2",
    time: "7: 45 am (15 Mins)",
    apptType: "New",
    intakeForm: "COMPLETED",
    dob: "6/19/14",
    contactNo: "505 555-0125",
    clinician: "Kristin Watson",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
  {
    clientName: "Robert Fox",
    apptMode: "Location 1",
    time: "8: 00 am (15 Mins)",
    apptType: "Follow Up",
    intakeForm: "COMPLETED",
    dob: "1/31/14",
    contactNo: "252 555-0126",
    clinician: "Courtney Henry",
    status: "SCHEDULED",
    action: [
      { label: "Start", route: "start" },
      { label: "More", route: "more" },
    ],
  },
];
