export const staffMockData = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    contact: "+1 555-123-4567",
    role: "Administrator",
    status: "Active",
    action: ["edit", "delete"],
  },
  {
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    contact: "+1 555-987-6543",
    role: "Nurse",
    status: "Active",
    action: ["edit", "delete"],
  },
  {
    name: "Michael Davis",
    email: "m.davis@example.com",
    contact: "+1 555-456-7890",
    role: "Doctor",
    status: "Inactive",
    action: ["edit", "delete"],
  },
];

export const clinicianMockData = [
  {
    name: "Jessica Williams",
    email: "j.williams@healthcare.org",
    contact: "+1 555-234-5678",
    npinumber: "1234567890",
    worklocation: "Main Hospital",
    status: "Active",
    action: ["edit", "delete"],
  },
  {
    name: "Robert Chen",
    email: "robert.chen@healthcare.org",
    contact: "+1 555-876-5432",
    npinumber: "2345678901",
    worklocation: "West Wing Clinic",
    status: "Active",
    action: ["edit", "delete"],
  },
  {
    name: "Amara Patel",
    email: "a.patel@healthcare.org",
    contact: "+1 555-345-6789",
    npinumber: "3456789012",
    worklocation: "East Side Medical Center",
    status: "Inactive",
    action: ["edit", "delete"],
  },
  {
    name: "Thomas Rodriguez",
    email: "t.rodriguez@healthcare.org",
    contact: "+1 555-654-3210",
    npinumber: "4567890123",
    worklocation: "South Branch Office",
    status: "Active",
    action: ["edit", "delete"],
  },
];

export const contactMockData = [
  {
    uuid: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 555-111-2222",
    fax: "+1 555-222-3333",
    address: "123 Main St, City, State 12345",
    contacttype: "Primary",
    action: ["edit", "delete"],
  },
  {
    uuid: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1 555-444-5555",
    fax: "+1 555-666-7777",
    address: "456 Oak Ave, City, State 12345",
    contacttype: "Secondary",
    action: ["edit", "delete"],
  },
];

export const rolesMockData = [
  {
    description: "Patients",
  },
  {
    description: "Create Edit View Patient",
    uuid: "create-edit-view-patient",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Patients",
    uuid: "view-patients",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Share Patients",
    uuid: "share-patients",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Appointments",
  },
  {
    description: "Create Appointments",
    uuid: "create-appointments",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Appointments",
    uuid: "view-appointments",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Appointment Clinician Selection",
    uuid: "appointment-clinician-selection",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Availability",
  },
  {
    description: "Create Availability",
    uuid: "create-availability",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "View Availability",
    uuid: "view-availability",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Have Availability",
    uuid: "have-availability",
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: "Documents - Intake",
    descriptionStyle: { fontWeight: "500" },
    isCategory: true,
    uuid: "cat-documents-intake",
    superAdmin: undefined,
    clinician: undefined,
    staff: undefined,
    client: undefined,
    recordCustodian: undefined,
  },
  {
    description: "Edit Intake Documents",
  },
];

export const locationTableData = [
  {
    locationName: "Main Clinic",
    contactNumber: "502-603-0020",
    email: "main@practiceeasily.com",
    groupNPI: "1234567890",
    fax: "502-603-0021",
    address: "205 Champion Way Suite 11 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Downtown Branch",
    contactNumber: "502-603-0022",
    email: "downtown@practiceeasily.com",
    groupNPI: "0987654321",
    fax: "502-603-0023",
    address: "123 Main Street Suite 4B Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Northside Clinic",
    contactNumber: "502-603-0024",
    email: "northside@practiceeasily.com",
    groupNPI: "1357924680",
    fax: "502-603-0025",
    address: "4580 North Ave Suite 201 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Southside Medical",
    contactNumber: "502-603-0026",
    email: "southside@practiceeasily.com",
    groupNPI: "2468135790",
    fax: "502-603-0027",
    address: "789 South Blvd Suite 30 Georgetown, KY 40324",
    status: "inactive",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Eastside Health Center",
    contactNumber: "502-603-0028",
    email: "eastside@practiceeasily.com",
    groupNPI: "3698521470",
    fax: "502-603-0029",
    address: "623 East Main Road Suite 5 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Westside Family Practice",
    contactNumber: "502-603-0030",
    email: "westside@practiceeasily.com",
    groupNPI: "7539514682",
    fax: "502-603-0031",
    address: "1024 West Park Avenue Suite 15 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Central Medical Plaza",
    contactNumber: "502-603-0032",
    email: "central@practiceeasily.com",
    groupNPI: "8642097531",
    fax: "502-603-0033",
    address: "500 Center Square Suite 220 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "River Valley Clinic",
    contactNumber: "502-603-0034",
    email: "river@practiceeasily.com",
    groupNPI: "9753108642",
    fax: "502-603-0035",
    address: "278 Riverside Drive Suite 8 Georgetown, KY 40324",
    status: "inactive",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Hillside Medical Center",
    contactNumber: "502-603-0036",
    email: "hillside@practiceeasily.com",
    groupNPI: "3216549870",
    fax: "502-603-0037",
    address: "853 Highland Road Suite 105 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Meadowview Health",
    contactNumber: "502-603-0038",
    email: "meadow@practiceeasily.com",
    groupNPI: "6543219870",
    fax: "502-603-0039",
    address: "429 Meadow Lane Suite 12 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Lexington Satellite Office",
    contactNumber: "859-603-0040",
    email: "lexington@practiceeasily.com",
    groupNPI: "7890123456",
    fax: "859-603-0041",
    address: "2200 Richmond Road Suite 150 Lexington, KY 40502",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Louisville Extension",
    contactNumber: "502-703-0042",
    email: "louisville@practiceeasily.com",
    groupNPI: "4567890123",
    fax: "502-703-0043",
    address: "1500 Bardstown Road Suite 300 Louisville, KY 40204",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Pediatric Specialty Center",
    contactNumber: "502-603-0044",
    email: "pediatric@practiceeasily.com",
    groupNPI: "5678901234",
    fax: "502-603-0045",
    address: "375 Children's Way Suite 20 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
  {
    locationName: "Senior Care Facility",
    contactNumber: "502-603-0046",
    email: "seniorcare@practiceeasily.com",
    groupNPI: "6789012345",
    fax: "502-603-0047",
    address: "950 Eldercare Road Suite 45 Georgetown, KY 40324",
    status: "active",
    action: [
      { label: "Edit", route: "edit" },
      { label: "Delete", route: "delete" },
    ],
  },
];

export const practiceData = {
  name: "Practice Easily",
  clinicNPI: "2365987458",
  emailID: "abc@example.com",
  taxType: "TIN",
  taxonomyCode: "1234567890",
  taxNumber: "123456",
  address: "205 Champion Way Suite 11 Georgetown, KY 40324",
  contactNumber: "502-603-0020",
};
